language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    # Needs to be here
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    # 22 emulator seems to be decent
    - android-22
    - sys-img-armeabi-v7a-android-22

    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

branches:
  only:
  - master

before_install:
  - adb logcat > logcat.log &

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - QEMU_AUDIO_DRV=none emulator -avd test -no-window &
  - android-wait-for-emulator
    # Unlock screen
  - adb shell input keyevent 82 &

after_failure:
  - cat logcat.log